### ISSUE TITLE
Offset with vertical scrolling

### ISSUE THREAD

**Issue by theskyisthelimit** [jalibu/MMM-Jast#22]
Platform (Hardware/OS):

Magicmirror Docker Container

Node version:

npm: '6.14.13'

MagicMirror version:

karsten13/magicmirror:v2.15.0

Module version:

v2.4.3

Description of the issue:

Just found this module and I love it. Just a little problem with the vertical scrolling. there seems to be some sort of offset.

![Jul-17-2021 16-52-17](https://user-images.githubusercontent.com/11703464/126040752-4e957a33-8fbe-457a-adcc-48404fe04228.gif)

any ideas?

**Comment by jalibu** [comment]
maaaaaaaaaaahhhhh :'-(

I thought this was solved... I'll fix this asap. Thank you for reporting

**Comment by theskyisthelimit** [comment]
Thanks for the quick reply! Looking forward. Enjoy the weekend👍🏼

**Comment by jalibu** [comment]
@theskyisthelimit do you use any custom css? whats your screen resolution?

**Comment by jalibu** [comment]
oh, and on which position do you place it?

**Comment by jalibu** [comment]
I can't reproduce it locally... Could you please send me your config.js?

**Comment by theskyisthelimit** [comment]
my screen resolution is 1920x1080

yes, I use the following entries in my custom.css. I also deleted all content and tried again. no change.

I tried bottom_right & bottom_right

```css
header {

  font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
}

.MMM-bernwordclock {
    font-family: "Courier";
}

body {

  margin: 5px;
  position: absolute;
  height: calc(100%);
  width: calc(100% - 5px);
  font-family: "Helvetica Neue", sans-serif;
  -webkit-font-smoothing: antialiased;
}
  .thin {
    font-family: "Helvetica Neue", sans-serif;
    font-weight: 100;
  }

  .light {
    font-family: "Helvetica Neue", sans-serif;
    font-weight: 300;
  }

  .regular {
    font-family: "Helvetica Neue", sans-serif;
    font-weight: 400;
  }

  .bold {
    font-family: "Helvetica Neue", sans-serif;
    font-weight: 700;
  }



.clock .time {
  	color: white;
	font-size: 100px;
	padding-top: 25px;
}


.brightb {
color: #55acee;
}
.currentweather .wi-sunrise {
color: #ffd700;
}
.currentweather .wi-sunset {
color: #ffa500;
}
.currentweather .wi-day-sunny {
color: #ffff00;
}
.currentweather .wi-night-showers {
color: #55acee;
}
.currentweather .wi-degrees {
color: #415;
}
.currentweather .wi-rain {
color: #55acee;
}
.currentweather .wi-showers {
color: #55acee;
}
.currentweather .wi-night-showers {
color: #55acee;
}
.currentweather .wi-night-alt-cloudy-windy {
color: #aaa;
}
.currentweather .wi-night-cloudy {
color: #aaa;
}
.currentweather .wi-cloudy {
color: #aaa;
}
.currentweather .wi-day-cloudy {
color: #aaa;
}
.currentweather .wi-cloudy {
color: #aaa;
}
.currentweather .wi-cloudy-windy {
color: #aaa;
}
.currentweather .wi-showers {
color: #55acee;
}
.currentweather .wi-thunderstorm {
color: #ff00ff;
}
.currentweather .wi-snow {
color: #fff;
}
.currentweather .wi-fog {
color: #999;
}
.currentweather .wi-night-clear {
color: #fff;
}
.currentweather .wi-night-rain {
color: #55acee;
}
.currentweather .wi-night-thunderstorm {
color: #ff00ff;
}
.currentweather .wi-night-snow {
color: #fff;
}

.weatherforecast .wi-sunrise {
color: #ffd700;
}
.weatherforecast .wi-sunset {
color: #ffa500;
}
.weatherforecast .wi-day-sunny {
color: #ffff00;
}
.weatherforecast .wi-night-showers {
color: #55acee;
}
.weatherforecast .wi-degrees {
color: #415;
}
.weatherforecast .wi-rain {
color: #55acee;
}
.weatherforecast .wi-showers {
color: #55acee;
}
.weatherforecast .wi-night-showers {
color: #55acee;
}
.weatherforecast .wi-night-alt-cloudy-windy {
color: #aaa;
}
.weatherforecast .wi-night-cloudy {
color: #aaa;
}
.weatherforecast .wi-cloudy {
color: #aaa;
}
.weatherforecast .wi-day-cloudy {
color: #aaa;
}
.weatherforecast .wi-cloudy {
color: #aaa;
}
.weatherforecast .wi-cloudy-windy {
color: #aaa;
}
.weatherforecast .wi-showers {
color: #55acee;
}
.weatherforecast .wi-thunderstorm {
color: #ff00ff;
}
.weatherforecast .wi-snow {
color: #fff;
}
.weatherforecast .wi-fog {
color: #999;
}
.weatherforecast .wi-night-clear {
color: #fff;
}
.weatherforecast .wi-night-rain {
color: #55acee;
}
.weatherforecast .wi-night-thunderstorm {
color: #ff00ff;
}
.currentweather .wi-night-snow {
color: #fff;
}

}

```
